# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-on-all:  
    # The type of runner that the job will run on
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Step 1 - checkout aix360 repository
        uses: actions/checkout@v3
      
      - name: Step 2 - set up python version
        uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'

      - name: Step 3 - upgrade setuptools
        run: pip3 install --upgrade setuptools
        
      - name: Step 4 - Install aix360         
        run: pip3 install .
      
      - name: Step 5 - Test CEM MAF
        run: python ./tests/contrastive/test_CEM_MAF.py
        
      - name: Step 6 - Test CEM
        run: python ./tests/contrastive/test_CEM.py
        
      - name: Step 7 - Test Protodash
        run: python ./tests/protodash/test_PDASH.py
        
      - name: Step 8 - Test TED
        run: python ./tests/ted/test_TED_Cartesian.py
        
      - name: Step 9 - Test DIPVAE
        run: python ./tests/dipvae/test_DIPVAE.py

      - name: Step 10 - Test BRCG
        run: python ./tests/rbm/test_Boolean_Rule_CG.py
        
      - name: Step 11 - Test Linear Rule Regression
        run: python ./tests/rbm/test_Linear_Rule_Regression.py
        
      - name: Step 12 - Test Logistic Rule Regression
        run: python ./tests/rbm/test_Logistic_Rule_Regression.py

      - name: Step 13 - Test Rule Induction
        run: bash ./tests/rule_induction/test_rule_induction.sh
